// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoGipWDQ9s6ChQ-QQM8CzLsNAyXEfHT0',
    appId: '1:79164243952:web:c0299c6cb8a3a6bee06735',
    messagingSenderId: '79164243952',
    projectId: 'movie-882df',
    authDomain: 'movie-882df.firebaseapp.com',
    storageBucket: 'movie-882df.firebasestorage.app',
    measurementId: 'G-P18HGTPQYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwCkwBAf_EvQ_MqSlSn77xenOI-YrEQE',
    appId: '1:79164243952:android:584ab3ba656490dbe06735',
    messagingSenderId: '79164243952',
    projectId: 'movie-882df',
    storageBucket: 'movie-882df.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVoGipWDQ9s6ChQ-QQM8CzLsNAyXEfHT0',
    appId: '1:79164243952:web:5bc2752b14a169d6e06735',
    messagingSenderId: '79164243952',
    projectId: 'movie-882df',
    authDomain: 'movie-882df.firebaseapp.com',
    storageBucket: 'movie-882df.firebasestorage.app',
    measurementId: 'G-1ZWGCQ8E6F',
  );
}
